/*
 * FINBOURNE Notifications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.296
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.notifications.model;

import java.util.Objects;
import java.util.Arrays;
import com.finbourne.notifications.model.AttemptStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * DeliveryAttempt
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DeliveryAttempt {
  public static final String SERIALIZED_NAME_ATTEMPT_NUMBER = "attemptNumber";
  @SerializedName(SERIALIZED_NAME_ATTEMPT_NUMBER)
  private Integer attemptNumber;

  public static final String SERIALIZED_NAME_ATTEMPTED_TIME = "attemptedTime";
  @SerializedName(SERIALIZED_NAME_ATTEMPTED_TIME)
  private OffsetDateTime attemptedTime;

  public static final String SERIALIZED_NAME_ATTEMPT_STATUS = "attemptStatus";
  @SerializedName(SERIALIZED_NAME_ATTEMPT_STATUS)
  private AttemptStatus attemptStatus;


  public DeliveryAttempt attemptNumber(Integer attemptNumber) {
    this.attemptNumber = attemptNumber; 
    return this;
  }

   /**
   * Get attemptNumber
   * @return attemptNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getAttemptNumber() {
    return attemptNumber;
  }

  public void setAttemptNumber(Integer attemptNumber) {
    this.attemptNumber = attemptNumber;
  }


  public DeliveryAttempt attemptedTime(OffsetDateTime attemptedTime) {
    this.attemptedTime = attemptedTime; 
    return this;
  }

   /**
   * Get attemptedTime
   * @return attemptedTime
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getAttemptedTime() {
    return attemptedTime;
  }

  public void setAttemptedTime(OffsetDateTime attemptedTime) {
    this.attemptedTime = attemptedTime;
  }


  public DeliveryAttempt attemptStatus(AttemptStatus attemptStatus) {
    this.attemptStatus = attemptStatus; 
    return this;
  }

   /**
   * Get attemptStatus
   * @return attemptStatus
  **/
  @ApiModelProperty(required = true, value = "")
  public AttemptStatus getAttemptStatus() {
    return attemptStatus;
  }

  public void setAttemptStatus(AttemptStatus attemptStatus) {
    this.attemptStatus = attemptStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return super.hashCode();  
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryAttempt {\n");
    sb.append("    attemptNumber: ").append(toIndentedString(attemptNumber)).append("\n");
    sb.append("    attemptedTime: ").append(toIndentedString(attemptedTime)).append("\n");
    sb.append("    attemptStatus: ").append(toIndentedString(attemptStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
