/*
 * FINBOURNE Notifications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.296
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.notifications.model;

import java.util.Objects;
import java.util.Arrays;
import com.finbourne.notifications.model.DeliveryAttempt;
import com.finbourne.notifications.model.ResourceId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * UndeliveredMessage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UndeliveredMessage {
  public static final String SERIALIZED_NAME_DELIVERY_ID = "deliveryId";
  @SerializedName(SERIALIZED_NAME_DELIVERY_ID)
  private UUID deliveryId;

  public static final String SERIALIZED_NAME_EVENT_ID = "eventId";
  @SerializedName(SERIALIZED_NAME_EVENT_ID)
  private UUID eventId;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_IDENTIFIER = "subscriptionIdentifier";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_IDENTIFIER)
  private ResourceId subscriptionIdentifier;

  public static final String SERIALIZED_NAME_NOTIFICATION_ID = "notificationId";
  @SerializedName(SERIALIZED_NAME_NOTIFICATION_ID)
  private UUID notificationId;

  public static final String SERIALIZED_NAME_DELIVERY_CHANNEL = "deliveryChannel";
  @SerializedName(SERIALIZED_NAME_DELIVERY_CHANNEL)
  private String deliveryChannel;

  public static final String SERIALIZED_NAME_MESSAGE_DETAILS = "messageDetails";
  @SerializedName(SERIALIZED_NAME_MESSAGE_DETAILS)
  private String messageDetails;

  public static final String SERIALIZED_NAME_DELIVERY_ATTEMPTS = "deliveryAttempts";
  @SerializedName(SERIALIZED_NAME_DELIVERY_ATTEMPTS)
  private List<DeliveryAttempt> deliveryAttempts = new ArrayList<>();


  public UndeliveredMessage deliveryId(UUID deliveryId) {
    this.deliveryId = deliveryId; 
    return this;
  }

   /**
   * Get deliveryId
   * @return deliveryId
  **/
  @ApiModelProperty(required = true, value = "")
  public UUID getDeliveryId() {
    return deliveryId;
  }

  public void setDeliveryId(UUID deliveryId) {
    this.deliveryId = deliveryId;
  }


  public UndeliveredMessage eventId(UUID eventId) {
    this.eventId = eventId; 
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  @ApiModelProperty(required = true, value = "")
  public UUID getEventId() {
    return eventId;
  }

  public void setEventId(UUID eventId) {
    this.eventId = eventId;
  }


  public UndeliveredMessage subscriptionIdentifier(ResourceId subscriptionIdentifier) {
    this.subscriptionIdentifier = subscriptionIdentifier; 
    return this;
  }

   /**
   * Get subscriptionIdentifier
   * @return subscriptionIdentifier
  **/
  @ApiModelProperty(required = true, value = "")
  public ResourceId getSubscriptionIdentifier() {
    return subscriptionIdentifier;
  }

  public void setSubscriptionIdentifier(ResourceId subscriptionIdentifier) {
    this.subscriptionIdentifier = subscriptionIdentifier;
  }


  public UndeliveredMessage notificationId(UUID notificationId) {
    this.notificationId = notificationId; 
    return this;
  }

   /**
   * Get notificationId
   * @return notificationId
  **/
  @ApiModelProperty(required = true, value = "")
  public UUID getNotificationId() {
    return notificationId;
  }

  public void setNotificationId(UUID notificationId) {
    this.notificationId = notificationId;
  }


  public UndeliveredMessage deliveryChannel(String deliveryChannel) {
    this.deliveryChannel = deliveryChannel; 
    return this;
  }

   /**
   * Get deliveryChannel
   * @return deliveryChannel
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDeliveryChannel() {
    return deliveryChannel;
  }

  public void setDeliveryChannel(String deliveryChannel) {
    this.deliveryChannel = deliveryChannel;
  }


  public UndeliveredMessage messageDetails(String messageDetails) {
    this.messageDetails = messageDetails; 
    return this;
  }

   /**
   * Get messageDetails
   * @return messageDetails
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMessageDetails() {
    return messageDetails;
  }

  public void setMessageDetails(String messageDetails) {
    this.messageDetails = messageDetails;
  }


  public UndeliveredMessage deliveryAttempts(List<DeliveryAttempt> deliveryAttempts) {
    this.deliveryAttempts = deliveryAttempts; 
    return this;
  }

  public UndeliveredMessage addDeliveryAttemptsItem(DeliveryAttempt deliveryAttemptsItem) {
   
    this.deliveryAttempts.add(deliveryAttemptsItem);
    return this;
  }

   /**
   * Get deliveryAttempts
   * @return deliveryAttempts
  **/
  @ApiModelProperty(required = true, value = "")
  public List<DeliveryAttempt> getDeliveryAttempts() {
    return deliveryAttempts;
  }

  public void setDeliveryAttempts(List<DeliveryAttempt> deliveryAttempts) {
    this.deliveryAttempts = deliveryAttempts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return super.hashCode();  
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UndeliveredMessage {\n");
    sb.append("    deliveryId: ").append(toIndentedString(deliveryId)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    subscriptionIdentifier: ").append(toIndentedString(subscriptionIdentifier)).append("\n");
    sb.append("    notificationId: ").append(toIndentedString(notificationId)).append("\n");
    sb.append("    deliveryChannel: ").append(toIndentedString(deliveryChannel)).append("\n");
    sb.append("    messageDetails: ").append(toIndentedString(messageDetails)).append("\n");
    sb.append("    deliveryAttempts: ").append(toIndentedString(deliveryAttempts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
