/*
 * FINBOURNE Notifications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.731
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.notifications.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The information required to create a notification which, when processed, will send an notification to Amazon SQS
 */
@ApiModel(description = "The information required to create a notification which, when processed, will send an notification to Amazon SQS")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdateAwsSqsNotification {
  public static final String SERIALIZED_NAME_API_KEY_REF = "apiKeyRef";
  @SerializedName(SERIALIZED_NAME_API_KEY_REF)
  private String apiKeyRef;

  public static final String SERIALIZED_NAME_API_SECRET_REF = "apiSecretRef";
  @SerializedName(SERIALIZED_NAME_API_SECRET_REF)
  private String apiSecretRef;

  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  private String body;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_QUEUE_URL_REF = "queueUrlRef";
  @SerializedName(SERIALIZED_NAME_QUEUE_URL_REF)
  private String queueUrlRef;


  public UpdateAwsSqsNotification apiKeyRef(String apiKeyRef) {
    this.apiKeyRef = apiKeyRef; 
    return this;
  }

   /**
   * Reference to API key from Configuration Store
   * @return apiKeyRef
  **/
  @ApiModelProperty(required = true, value = "Reference to API key from Configuration Store")
  public String getApiKeyRef() {
    return apiKeyRef;
  }

  public void setApiKeyRef(String apiKeyRef) {
    this.apiKeyRef = apiKeyRef;
  }


  public UpdateAwsSqsNotification apiSecretRef(String apiSecretRef) {
    this.apiSecretRef = apiSecretRef; 
    return this;
  }

   /**
   * Reference to API secret from Configuration Store
   * @return apiSecretRef
  **/
  @ApiModelProperty(required = true, value = "Reference to API secret from Configuration Store")
  public String getApiSecretRef() {
    return apiSecretRef;
  }

  public void setApiSecretRef(String apiSecretRef) {
    this.apiSecretRef = apiSecretRef;
  }


  public UpdateAwsSqsNotification body(String body) {
    this.body = body; 
    return this;
  }

   /**
   * The body of the Amazon Queue Message
   * @return body
  **/
  @ApiModelProperty(required = true, value = "The body of the Amazon Queue Message")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }


  public UpdateAwsSqsNotification description(String description) {
    this.description = description; 
    return this;
  }

   /**
   * The summary of the services provided by the notification
   * @return description
  **/
  @ApiModelProperty(required = true, value = "The summary of the services provided by the notification")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public UpdateAwsSqsNotification queueUrlRef(String queueUrlRef) {
    this.queueUrlRef = queueUrlRef; 
    return this;
  }

   /**
   * Reference to queue url from Configuration Store
   * @return queueUrlRef
  **/
  @ApiModelProperty(required = true, value = "Reference to queue url from Configuration Store")
  public String getQueueUrlRef() {
    return queueUrlRef;
  }

  public void setQueueUrlRef(String queueUrlRef) {
    this.queueUrlRef = queueUrlRef;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return super.hashCode();  
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateAwsSqsNotification {\n");
    sb.append("    apiKeyRef: ").append(toIndentedString(apiKeyRef)).append("\n");
    sb.append("    apiSecretRef: ").append(toIndentedString(apiSecretRef)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    queueUrlRef: ").append(toIndentedString(queueUrlRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
