/*
 * FINBOURNE Notifications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.315
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.notifications.api;

import com.finbourne.notifications.ApiException;
import com.finbourne.notifications.model.LusidProblemDetails;
import com.finbourne.notifications.model.LusidValidationProblemDetails;
import com.finbourne.notifications.model.ResourceListOfDelivery;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeliveriesApi
 */
@Ignore
public class DeliveriesApiTest {

    private final DeliveriesApi api = new DeliveriesApi();

    
    /**
     * [EXPERIMENTAL] ListDeliveries: List Deliveries
     *
     * Currently only returns deliveries with failed attempts.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDeliveriesTest() throws ApiException {
        String page = null;
        Integer limit = null;
        String filter = null;
        ResourceListOfDelivery response = api.listDeliveries(page, limit, filter);

        // TODO: test validations
    }
    
}
