/*
 * FINBOURNE Notifications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.296
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.notifications.api;

import com.finbourne.notifications.ApiException;
import com.finbourne.notifications.model.EventTypeSchema;
import com.finbourne.notifications.model.LusidProblemDetails;
import com.finbourne.notifications.model.LusidValidationProblemDetails;
import com.finbourne.notifications.model.ResourceListOfEventTypeSchema;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EventTypesApi
 */
@Ignore
public class EventTypesApiTest {

    private final EventTypesApi api = new EventTypesApi();

    
    /**
     * [EXPERIMENTAL] GetEventType: Gets the specified event type schema.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEventTypeTest() throws ApiException {
        String eventType = null;
        EventTypeSchema response = api.getEventType(eventType);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] ListEventTypes: Lists all of the available event types.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listEventTypesTest() throws ApiException {
        ResourceListOfEventTypeSchema response = api.listEventTypes();

        // TODO: test validations
    }
    
}
