version: "3"

services:

  lusid-sdk-java-preview-test:
    build: .
    container_name: notifications-sdk-java-preview-test
    image: maven:3.8.5-jdk-11
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_APP_NAME
      - FBN_NOTIFICATIONS_API_URL=${FBN_BASE_API_URL}/notifications
      - FBN_ACCESS_TOKEN
    volumes:
      - .:/usr/src