/*
 * FINBOURNE Notifications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.315
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.notifications.model;

import com.finbourne.notifications.model.AttemptStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Attempt
 */
public class AttemptTest {
    private final Attempt model = new Attempt();

    /**
     * Model tests for Attempt
     */
    @Test
    public void testAttempt() {
        // TODO: test Attempt
    }

    /**
     * Test the property 'attemptNumber'
     */
    @Test
    public void attemptNumberTest() {
        // TODO: test attemptNumber
    }

    /**
     * Test the property 'attemptTime'
     */
    @Test
    public void attemptTimeTest() {
        // TODO: test attemptTime
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
