/*
 * FINBOURNE Notifications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.296
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.notifications.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateEmailNotification
 */
public class CreateEmailNotificationTest {
    private final CreateEmailNotification model = new CreateEmailNotification();

    /**
     * Model tests for CreateEmailNotification
     */
    @Test
    public void testCreateEmailNotification() {
        // TODO: test CreateEmailNotification
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'plainTextBody'
     */
    @Test
    public void plainTextBodyTest() {
        // TODO: test plainTextBody
    }

    /**
     * Test the property 'htmlBody'
     */
    @Test
    public void htmlBodyTest() {
        // TODO: test htmlBody
    }

    /**
     * Test the property 'emailAddressTo'
     */
    @Test
    public void emailAddressToTest() {
        // TODO: test emailAddressTo
    }

    /**
     * Test the property 'emailAddressCc'
     */
    @Test
    public void emailAddressCcTest() {
        // TODO: test emailAddressCc
    }

    /**
     * Test the property 'emailAddressBcc'
     */
    @Test
    public void emailAddressBccTest() {
        // TODO: test emailAddressBcc
    }

}
