/*
 * FINBOURNE Notifications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.296
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.notifications.model;

import com.finbourne.notifications.model.AttemptStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeliveryAttempt
 */
public class DeliveryAttemptTest {
    private final DeliveryAttempt model = new DeliveryAttempt();

    /**
     * Model tests for DeliveryAttempt
     */
    @Test
    public void testDeliveryAttempt() {
        // TODO: test DeliveryAttempt
    }

    /**
     * Test the property 'attemptNumber'
     */
    @Test
    public void attemptNumberTest() {
        // TODO: test attemptNumber
    }

    /**
     * Test the property 'attemptedTime'
     */
    @Test
    public void attemptedTimeTest() {
        // TODO: test attemptedTime
    }

    /**
     * Test the property 'attemptStatus'
     */
    @Test
    public void attemptStatusTest() {
        // TODO: test attemptStatus
    }

}
