/*
 * FINBOURNE Notifications API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.296
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.notifications.model;

import com.finbourne.notifications.model.DeliveryAttempt;
import com.finbourne.notifications.model.ResourceId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UndeliveredMessage
 */
public class UndeliveredMessageTest {
    private final UndeliveredMessage model = new UndeliveredMessage();

    /**
     * Model tests for UndeliveredMessage
     */
    @Test
    public void testUndeliveredMessage() {
        // TODO: test UndeliveredMessage
    }

    /**
     * Test the property 'deliveryId'
     */
    @Test
    public void deliveryIdTest() {
        // TODO: test deliveryId
    }

    /**
     * Test the property 'eventId'
     */
    @Test
    public void eventIdTest() {
        // TODO: test eventId
    }

    /**
     * Test the property 'subscriptionIdentifier'
     */
    @Test
    public void subscriptionIdentifierTest() {
        // TODO: test subscriptionIdentifier
    }

    /**
     * Test the property 'notificationId'
     */
    @Test
    public void notificationIdTest() {
        // TODO: test notificationId
    }

    /**
     * Test the property 'deliveryChannel'
     */
    @Test
    public void deliveryChannelTest() {
        // TODO: test deliveryChannel
    }

    /**
     * Test the property 'messageDetails'
     */
    @Test
    public void messageDetailsTest() {
        // TODO: test messageDetails
    }

    /**
     * Test the property 'deliveryAttempts'
     */
    @Test
    public void deliveryAttemptsTest() {
        // TODO: test deliveryAttempts
    }

}
